### ISSUE TITLE
[FE] : [FEAT] 커뮤니티 페이지 제작 

### ISSUE THREAD

**Issue by mjseok** [mjseok/Tripful#17]
### 🌞 이슈 요약
커뮤니티 페이지 제작 

### ✅ 체크 리스트

- [ ] 공지 페이지
- [ ] 게시판 페이지(스케줄 등록)
- [ ] 관련 BE(CRUD)

**Comment by tykwon97** [comment]
민지
- 2. 스케줄
- 1. 게시판(커뮤니티) - CRUD ->
태윤
- 2. 로그인쪽
- 1. 마이페이지 (정보수정+페이지)

마지막
- 카카오 로그인
- 깃헙 로그인

커뮤니티(공지사항, 스케줄 등록)
